version: "3.7"

services:
    component-authentication:
        image: parisnk/component-logging
        ports:
            - "5000:5000"

        environment:
            - MONGO_DATABASE=component-authentication
            - MONGO_HOST=host.docker.internal
            - MONGO_PORT=27017
            - MONGO_USERNAME=mongoadmin
            - MONGO_PASSWORD=secret
            - MONGO_AUTH_SOURCE=admin
            - MONGO_MECHANISM=SCRAM-SHA-1
            - DEBUG_MODE=0
